In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
df=pd.read_csv('/Users/vedantgupta/Documents/summer project/data-analysis-with-technical-indicators-2/Pair trading/notebooks/Orders_strat_1.csv')
stock=pd.read_csv('/Users/vedantgupta/Documents/summer project/data-analysis-with-technical-indicators-2/Pair trading/Returns data/sensex_close.csv')

In [36]:
groups = [['SUNPHARMA.NS', 'TATAMOTORS.NS', 'TCS.NS', 'TECHM.NS', 'WIPRO.NS', 'HCLTECH.NS', 'INFY.NS'],
          ['MARUTI.NS', 'POWERGRID.NS', 'SBIN.NS', 'AXISBANK.NS', 'ICICIBANK.NS'],
          ['NESTLEIND.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'ASIANPAINT.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'HDFCBANK.NS', 'HINDUNILVR.NS', 'INDUSINDBK.NS', 'ITC.NS', 'KOTAKBANK.NS'],
          ['RELIANCE.NS', 'JSWSTEEL.NS']]

In [37]:
for i in range(1,len(stock.columns)):
    stock.columns.values[i] = stock.columns.values[i][:-7]

In [38]:
#standardise stock prices

for group in groups:
    for stock_name in group:
        stock[stock_name] = stock[stock_name]/stock[stock_name][0]

In [39]:
stock

,Date,M&M.NS,MARUTI.NS,NESTLEIND.NS,NTPC.NS,POWERGRID.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TATAMOTORS.NS,...,HCLTECH.NS,HDFCBANK.NS,HINDUNILVR.NS,ICICIBANK.NS,INDUSINDBK.NS,INFY.NS,ITC.NS,JSWSTEEL.NS,KOTAKBANK.NS,LT.NS
0,2011-01-03,354.620422,1.000000,1.000000,103.102730,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,730.862915
1,2011-01-04,351.783600,1.001893,1.014534,103.985962,1.001017,1.020368,0.969349,1.005336,0.992319,...,1.015413,0.981196,1.024749,0.964362,0.966371,1.006680,1.015446,0.980354,1.007438,729.054565
2,2011-01-05,347.190735,0.990463,1.016971,103.648254,0.997966,1.019136,0.954325,1.001539,0.980397,...,1.040075,0.965572,1.040077,0.934052,0.941054,1.000362,1.028604,0.963395,0.982061,711.673218
3,2011-01-06,347.280792,0.963430,0.999465,104.947121,1.007121,1.028420,0.929237,1.026062,0.963736,...,1.051855,0.973750,1.024269,0.920164,0.921595,1.005725,1.023455,0.923138,0.973747,693.000366
4,2011-01-07,333.344513,0.940044,0.988034,102.375381,0.995422,1.009284,0.921636,1.012415,0.909626,...,1.024442,0.949362,0.999681,0.916452,0.870017,0.974670,0.986842,0.864705,0.952089,681.320557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,2023-12-22,1634.250000,7.916517,7.664788,300.772919,6.663794,5.890295,2.604811,5.546443,2.949405,...,16.974611,7.692729,10.284628,5.554849,6.366617,4.782683,5.312453,8.425057,8.213008,3477.949951
3200,2023-12-26,1662.250000,7.957970,7.723283,307.527405,6.709801,5.920148,2.610129,5.563613,2.928445,...,16.921811,7.746136,10.321165,5.559319,6.401051,4.724694,5.327041,8.395506,8.329327,3490.050049
3201,2023-12-27,1687.949951,7.971801,7.771141,304.001160,6.729929,5.940356,2.653082,5.585689,3.015336,...,17.083121,7.842132,10.415202,5.599264,6.509650,4.795536,5.334627,8.627976,8.397751,3544.000000
3202,2023-12-28,1734.449951,7.958706,7.931109,311.798615,6.875138,5.983298,2.664741,5.628949,3.068244,...,17.087761,7.851109,10.517026,5.619655,6.563033,4.781918,5.416322,8.676242,8.481624,3518.050049
3203,2023-12-29,1729.400024,7.982532,8.030935,309.067017,6.820505,5.935993,2.626492,5.616907,3.174263,...,17.014069,7.869526,10.637418,5.567699,6.515763,4.721481,5.392980,8.670825,8.423133,3526.000000

In [58]:
stock_group = pd.DataFrame()
stock_group['Date'] = stock['Date']
stock_group['Date']=pd.to_datetime(stock_group['Date'])

for group in groups:
    for stock_name in group:
        stock_group[stock_name] = stock[stock_name]

stock_group

,Date,SUNPHARMA.NS,TATAMOTORS.NS,TCS.NS,TECHM.NS,WIPRO.NS,HCLTECH.NS,INFY.NS,MARUTI.NS,POWERGRID.NS,...,ASIANPAINT.NS,BAJFINANCE.NS,BAJAJFINSV.NS,HDFCBANK.NS,HINDUNILVR.NS,INDUSINDBK.NS,ITC.NS,KOTAKBANK.NS,RELIANCE.NS,JSWSTEEL.NS
0,2011-01-03,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2011-01-04,1.005336,0.992319,0.988515,1.046301,1.003312,1.015413,1.006680,1.001893,1.001017,...,0.986659,0.993827,0.995323,0.981196,1.024749,0.966371,1.015446,1.007438,1.020368,0.980354
2,2011-01-05,1.001539,0.980397,1.000777,1.023748,1.005382,1.040075,1.000362,0.990463,0.997966,...,1.002070,0.989712,0.987989,0.965572,1.040077,0.941054,1.028604,0.982061,1.019136,0.963395
3,2011-01-06,1.026062,0.963736,1.011787,1.025574,1.006831,1.051855,1.005725,0.963430,1.007121,...,0.991285,0.977297,0.966199,0.973750,1.024269,0.921595,1.023455,0.973747,1.028420,0.923138
4,2011-01-07,1.012415,0.909626,0.986702,0.994450,0.987372,1.024442,0.974670,0.940044,0.995422,...,0.965630,0.936006,0.947810,0.949362,0.999681,0.870017,0.986842,0.952089,1.009284,0.864705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,2023-12-22,5.546443,2.949405,8.466182,9.171497,2.890848,16.974611,4.782683,7.916517,6.663794,...,12.896984,114.609199,36.672607,7.692729,10.284628,6.366617,5.312453,8.213008,5.890295,8.425057
3200,2023-12-26,5.563613,2.928445,8.403194,9.220765,2.937399,16.921811,4.724694,7.957970,6.709801,...,13.059292,112.519769,36.085906,7.746136,10.321165,6.401051,5.327041,8.329327,5.920148,8.395506
3201,2023-12-27,5.585689,3.015336,8.437843,9.207459,2.942711,17.083121,4.795536,7.971801,6.729929,...,13.140734,113.627324,36.615579,7.842132,10.415202,6.509650,5.334627,8.397751,5.940356,8.627976
3202,2023-12-28,5.628949,3.068244,8.412825,9.249175,2.933338,17.087761,4.781918,7.958706,6.875138,...,13.112943,114.033429,36.873289,7.851109,10.517026,6.563033,5.416322,8.481624,5.983298,8.676242
3203,2023-12-29,5.616907,3.174263,8.398435,9.153516,2.944897,17.014069,4.721481,7.982532,6.820505,...,13.132821,115.118992,36.974181,7.869526,10.637418,6.515763,5.392980,8.423133,5.935993,8.670825

In [59]:
df

          Date         Stock Order        Price
0   2011-04-07      TECHM.NS   Buy   146.584991
1   2011-04-07  SUNPHARMA.NS  Sell   201.884674
2   2011-05-26  SUNPHARMA.NS   Buy   201.633041
3   2011-05-26        TCS.NS  Sell   438.494690
4   2011-06-24       INFY.NS   Buy   272.191711
..         ...           ...   ...          ...
595 2016-09-12   JSWSTEEL.NS  Sell   159.174622
596 2023-12-29   RELIANCE.NS  Sell  2584.949951
597 2023-12-29   JSWSTEEL.NS   Buy   880.250000
598 2023-12-29   JSWSTEEL.NS  Sell   880.250000
599 2023-12-29   RELIANCE.NS   Buy  2584.949951

[600 rows x 4 columns]

In [67]:
signal_dict = {'Buy': 1, 'Sell': -1}
df['Order'] = df['Order'].map(signal_dict)

In [77]:
# add signal to stock_group from df

for group in groups:
    for stock_name in group:
        stock_group[stock_name + ' Signal'] = 0
        for i in range(len(df)):
            df['Stock'][i]=

stock_group

/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_group[stock_name + ' Signal'][stock_group['Date'] == df['Date'][i]] = df['Order'][i]
/var/folders/90/5g2l2f2j191dmr85qjr8jrn40000gn/T/ipykernel_11513/2572001414.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value


,Date,SUNPHARMA.NS,TATAMOTORS.NS,TCS.NS,TECHM.NS,WIPRO.NS,HCLTECH.NS,INFY.NS,MARUTI.NS,POWERGRID.NS,...,ASIANPAINT.NS Signal,BAJFINANCE.NS Signal,BAJAJFINSV.NS Signal,HDFCBANK.NS Signal,HINDUNILVR.NS Signal,INDUSINDBK.NS Signal,ITC.NS Signal,KOTAKBANK.NS Signal,RELIANCE.NS Signal,JSWSTEEL.NS Signal
0,2011-01-03,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2011-01-04,1.005336,0.992319,0.988515,1.046301,1.003312,1.015413,1.006680,1.001893,1.001017,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011-01-05,1.001539,0.980397,1.000777,1.023748,1.005382,1.040075,1.000362,0.990463,0.997966,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2011-01-06,1.026062,0.963736,1.011787,1.025574,1.006831,1.051855,1.005725,0.963430,1.007121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2011-01-07,1.012415,0.909626,0.986702,0.994450,0.987372,1.024442,0.974670,0.940044,0.995422,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,2023-12-22,5.546443,2.949405,8.466182,9.171497,2.890848,16.974611,4.782683,7.916517,6.663794,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3200,2023-12-26,5.563613,2.928445,8.403194,9.220765,2.937399,16.921811,4.724694,7.957970,6.709801,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3201,2023-12-27,5.585689,3.015336,8.437843,9.207459,2.942711,17.083121,4.795536,7.971801,6.729929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3202,2023-12-28,5.628949,3.068244,8.412825,9.249175,2.933338,17.087761,4.781918,7.958706,6.875138,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3203,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
df['Stock'][0]

'TECHM.NS'