In [2]:
import yfinance as yf
import numpy as np
import pandas as pd

In [3]:
tcs_data = pd.DataFrame(yf.Ticker("TCS.NS").history(period="1mo"))
tcs_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-04-16 00:00:00+05:30,3873.844233,3900.351524,3834.976825,3844.854980,3051420,0.0,0.0
2024-04-18 00:00:00+05:30,3848.826068,3907.598848,3822.219401,3834.132812,3476284,0.0,0.0
2024-04-19 00:00:00+05:30,3810.305967,3824.751026,3773.473574,3798.591064,2957749,0.0,0.0
2024-04-22 00:00:00+05:30,3809.313169,3850.017323,3784.493563,3836.714111,1728883,0.0,0.0
2024-04-23 00:00:00+05:30,3849.074351,3866.894780,3832.743098,3846.741211,1807586,0.0,0.0
2024-04-24 00:00:00+05:30,3861.930835,3869.873109,3796.853777,3803.406250,1317312,0.0,0.0
2024-04-25 00:00:00+05:30,3783.699409,3845.698739,3783.500900,3824.403564,2856271,0.0,0.0
2024-04-26 00:00:00+05:30,3827.332036,3848.825960,3775.111731,3793.776123,2039178,0.0,0.0
2024-04-29 00:00:00+05:30,3810.306076,3849.818939,3791.641683,3842.273682,1110693,0.0,0.0
2024-04-30 00:00:00+05:30,3844.060623,3853.740269,3782.507999,3793.081055,2203078,0.0,0.0
2024-05-02 00:00:00+05:30,3750.788724,3843.167350,3750.788724,3835.423584,2491044,0.0,0.0
2024-05-03 00:00:00+05:30,3862.079657,3865.504957,3770.197666,3815.666992,2962234,0.0,0.0
2024-05-06 00:00:00+05:30,3825.197817,3911.520362,3825.197817,3892.756836,2053831,0.0,0.0
2024-05-07 00:00:00+05:30,3902.436306,3959.223515,3885.261090,3950.238770,2062112,0.0,0.0
2024-05-08 00:00:00+05:30,3932.418557,3955.550479,3910.180286,3948.253418,1247685,0.0,0.0
2024-05-09 00:00:00+05:30,3933.411328,3942.346386,3881.836233,3931.624268,1726486,0.0,0.0
2024-05-10 00:00:00+05:30,3934.006962,3944.927589,3857.016495,3865.802490,1672489,0.0,0.0
2024-05-13 00:00:00+05:30,3856.470429,3926.461719,3842.075057,3919.313721,931326,0.0,0.0
2024-05-14 00:00:00+05:30,3907.598745,3917.328078,3864.809647,3873.049805,1058317,0.0,0.0
2024-05-15 00:00:00+05:30,3876.326100,3898.614058,3847.535356,3852.399902,1115021,0.0,0.0
2024-05-16 00:00:00+05:30,3891.100098,3909.500000,3855.149902,3865.500000,1239656,28.0,0.0

In [4]:
tcs_data.reset_index(inplace=True)
tcs_data.rename(columns={"index": "Date"}, inplace=True)

In [5]:

tcs_data = tcs_data.drop(columns=['Volume','Dividends','Stock Splits'])
tcs_data

,Date,Open,High,Low,Close
0,2024-04-16 00:00:00+05:30,3873.844233,3900.351524,3834.976825,3844.854980
1,2024-04-18 00:00:00+05:30,3848.826068,3907.598848,3822.219401,3834.132812
2,2024-04-19 00:00:00+05:30,3810.305967,3824.751026,3773.473574,3798.591064
3,2024-04-22 00:00:00+05:30,3809.313169,3850.017323,3784.493563,3836.714111
4,2024-04-23 00:00:00+05:30,3849.074351,3866.894780,3832.743098,3846.741211
5,2024-04-24 00:00:00+05:30,3861.930835,3869.873109,3796.853777,3803.406250
6,2024-04-25 00:00:00+05:30,3783.699409,3845.698739,3783.500900,3824.403564
7,2024-04-26 00:00:00+05:30,3827.332036,3848.825960,3775.111731,3793.776123
8,2024-04-29 00:00:00+05:30,3810.306076,3849.818939,3791.641683,3842.273682
9,2024-04-30 00:00:00+05:30,3844.060623,3853.740269,3782.507999,3793.081055
10,2024-05-02 00:00:00+05:30,3750.788724,3843.167350,3750.788724,3835.423584
11,2024-05-03 00:00:00+05:30,3862.079657,3865.504957,3770.197666,3815.666992
12,2024-05-06 00:00:00+05:30,3825.197817,3911.520362,3825.197817,3892.756836
13,2024-05-07 00:00:00+05:30,3902.436306,3959.223515,3885.261090,3950.238770
14,2024-05-08 00:00:00+05:30,3932.418557,3955.550479,3910.180286,3948.253418
15,2024-05-09 00:00:00+05:30,3933.411328,3942.346386,3881.836233,3931.624268
16,2024-05-10 00:00:00+05:30,3934.006962,3944.927589,3857.016495,3865.802490
17,2024-05-13 00:00:00+05:30,3856.470429,3926.461719,3842.075057,3919.313721
18,2024-05-14 00:00:00+05:30,3907.598745,3917.328078,3864.809647,3873.049805
19,2024-05-15 00:00:00+05:30,3876.326100,3898.614058,3847.535356,3852.399902
20,2024-05-16 00:00:00+05:30,3891.100098,3909.500000,3855.149902,3865.500000

In [6]:
ticker_list =np.array(['M&M.NS','MARUTI.NS','NESTLEIND.NS','NTPC.NS','POWERGRID.NS','RELIANCE.NS','SBIN.NS','SUNPHARMA.NS','TATAMOTORS.NS','TATASTEEL.NS','TCS.NS','TECHM.NS','TITAN.NS','ULTRACEMCO.NS','WIPRO.NS','ASIANPAINT.NS','AXISBANK.NS','BAJFINANCE.NS','BAJAJFINSV.NS','BHARTIARTL.NS','HCLTECH.NS','HDFCBANK.NS','HINDUNILVR.NS','ICICIBANK.NS','INDUSINDBK.NS','INFY.NS','ITC.NS','JSWSTEEL.NS','KOTAKBANK.NS','LT.NS'])

In [7]:
trial = pd.DataFrame(yf.Ticker("TCS.NS").history(start="2011-01-01",
                                     end="2023-12-31"))
trial

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2011-01-03 00:00:00+05:30,449.801575,453.636626,445.002940,446.351959,1405042,0.0,0.0
2011-01-04 00:00:00+05:30,448.606626,449.473852,438.662410,441.225555,2502868,0.0,0.0
2011-01-05 00:00:00+05:30,441.418333,449.377556,440.069314,446.698761,3069674,0.0,0.0
2011-01-06 00:00:00+05:30,450.187041,455.583119,444.444064,451.613129,2846720,0.0,0.0
2011-01-07 00:00:00+05:30,453.270540,457.452491,438.681867,440.416321,2532724,0.0,0.0
...,...,...,...,...,...,...,...
2023-12-22 00:00:00+05:30,3755.179803,3800.587785,3717.628005,3778.896729,2413058,0.0,0.0
2023-12-26 00:00:00+05:30,3774.795661,3788.778668,3745.445774,3750.782227,1285231,0.0,0.0
2023-12-27 00:00:00+05:30,3754.191504,3773.164995,3723.557143,3766.247559,1293976,0.0,0.0
2023-12-28 00:00:00+05:30,3778.896652,3792.731525,3747.373003,3755.080811,1682889,0.0,0.0
2023-12-29 00:00:00+05:30,3747.274324,3777.513501,3720.987968,3748.657715,1574996,0.0,0.0

In [8]:
n = 3204

In [9]:
trial.reset_index(inplace=True)
trial.rename(columns={"index": "Date"}, inplace=True)

In [10]:
sensex_df = pd.DataFrame()
sensex_df['Date'] = trial['Date'].dt.date
sensex_df

            Date
0     2011-01-03
1     2011-01-04
2     2011-01-05
3     2011-01-06
4     2011-01-07
...          ...
3199  2023-12-22
3200  2023-12-26
3201  2023-12-27
3202  2023-12-28
3203  2023-12-29

[3204 rows x 1 columns]

In [11]:
sensex_df['Date'].dtype

dtype('O')

In [16]:
for x in ticker_list:
    d = pd.DataFrame(yf.Ticker(x).history(start="2011-01-01",
                                     end="2023-12-31"))
    l = []
    for i in range(n):
        para = []
        for j in range(4):
            para.append(str(d.iloc[i,j]))
        s = "/".join(para)
        l.append(s)
    
    sensex_df[x] = l

sensex_df

,Date,M&M.NS,MARUTI.NS,NESTLEIND.NS,NTPC.NS,POWERGRID.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TATAMOTORS.NS,...,HCLTECH.NS,HDFCBANK.NS,HINDUNILVR.NS,ICICIBANK.NS,INDUSINDBK.NS,INFY.NS,ITC.NS,JSWSTEEL.NS,KOTAKBANK.NS,LT.NS
0,2011-01-03,357.8624659280758/360.99193872661425/353.11198...,1294.186623378024/1312.2871355931013/1283.7788...,330.28754934205455/332.2062845207583/326.95774...,104.6353698760385/105.20686714016661/102.63514...,34.25778640983862/34.36217592098546/34.0490026...,439.3483666671774/439.96717707408254/434.23295...,245.36971264180482/247.04150723605585/243.8495...,226.47683601156973/226.47683601156973/221.8786...,249.32552726534496/250.69635955309664/244.3491...,...,85.4643412695165/85.4643412695165/83.838660864...,212.43509206114672/215.09276830587567/210.6782...,247.95287298686034/252.63123414624195/247.9128...,180.4273470773884/181.11528761165866/178.07429...,246.5562663746511/250.21892257718966/244.79449...,325.4271254709185/327.8555404635452/323.886916...,85.00079187341757/85.00079187341757/84.0104430...,101.88509386456226/103.4533404611882/100.61088...,226.92735923500695/227.94331304107092/225.9361...,732.6526765432103/735.5865049279827/726.988088...
1,2011-01-04,354.4177444559813/356.6241421875/349.059393152...,1291.4717469276302/1315.3644488540222/1270.701...,329.9692493997998/335.55333598714986/326.95779...,103.05078966456226/104.79124278686723/103.0507...,34.257789817787085/34.414376459916106/34.01420...,437.28573930102874/445.49514636463743/436.1719...,245.51699721985167/245.51699721985167/236.2269...,222.81660143811985/225.1042462167453/220.59758...,246.73404617129805/247.99221836658273/241.3163...,...,84.53537392024585/86.1982148620308/83.95941749...,213.91408745618193/214.0485482664944/209.11861...,251.11182529071345/263.82735551191536/250.7119...,179.12964278843813/179.67685654190694/171.6873...,245.72176428950544/247.06629092253576/236.0319...,326.6556099522027/330.6242346609076/326.655609...,84.54185872055994/86.03945665625126/84.5418587...,102.33255014317866/102.33255014317866/99.30258...,226.4813263900376/229.9504057876968/226.481326...,734.3686097301978/735.2173729523169/723.113222...
2,2011-01-05,351.7836273992247/355.27332098302503/344.55659...,1292.3764133650338/1298.7115918619213/1272.782...,333.32473020787575/338.5689601240239/331.81900...,103.80411643121477/104.40158440081362/102.8689...,34.240397302868864/34.39698397483902/33.996817...,445.5362997539789/449.6616560064768/441.410971...,236.90689119121666/237.02817248950754/232.3160...,224.87547752304187/228.7644735737964/221.97016...,244.12381441285882/245.98290774039214/239.6169...,...,85.65015449382396/88.25124378430885/85.4643624...,210.61552560264045/210.61552560264045/205.9365...,256.46991058616067/261.78803741843797/253.7108...,171.54667995695743/171.8281071671287/166.51223...,237.14468355428505/237.14468355428505/227.1767...,327.4114569932569/328.5453494850084/325.531094...,85.70127468219124/87.05394570195291/84.9283213...,100.1122788495297/100.1122788495297/97.4488115...,227.96805817715085/230.37163746751125/221.0298...,731.4532308298388/737.3207851251321/706.765159...
3,2011-01-06,349.8699196987059/350.3202027356412/341.314541...,1280.656372028957/1289.6613315215145/1236.5363...,335.5618488407969/339.7778770746762/327.387906...,103.67425347685482/105.07701206280194/102.6351...,34.170797763363886/34.71015386296575/34.031607...,444.71133882974453/450.2392704222824/443.28808...,235.0878781728218/235.0878781728218/226.347878...,224.18919097900388/230.1370674743652/223.73166...,242.09571019355857/244.2928126648854/234.42458...,...,88.1304868497848/89.44961193988279/88.07474581...,207.59480921640744/209.98357760249493/206.9673...,261.9479051950451/262.9475537790675/249.832169...,167.95842598194523/168.61509809949717/163.7369...,229.95849233901163/234.4093046979023/225.41496...,328.8288398794315/330.0572234766822/325.436620...,87.12640852964876/87.44042183802486/84.9524753...,98.24574307859665/99.20885726812963/93.2256391...,223.0122453580337/225.4405978938018/219.444043...,717.7622778734609/717.7622778734609/691.561198...
4,2011-01-07,344.10628806969225/344.8717746973949/329.62967...,1235.360134954369/1237.8036602613709/1210.5172...,327.8180927018704/332.9805823507188/324.548526...,104.89515432107082/105.57055333240405/101.6220...,34.44916583812546/34.76234142455732/33.8054203...,446.0726577446408/448.7335066418312/436.460621...,226.7636788747219/228.8512348496769/222.367680...,229.90828009587722/234.14042256530382/222.7708...,236.61232275920975/237.24140893025714/217.8335...,...,88.994414906038/90.85233588528723/85.650157143...,208.50906553811683/208.50906553811683/202.6648...,257.4295695924214/258.2292886805653/248.392753...,163.3852132390265/168.52910561435547/162.75980...,231.8129813891151/232.27660735189335/209.55893...,327.25558724474024/330.24621974959496/317.1450...,86.01528852820073/86.9573284646739/82.41622095...,93.66882717084592/93.72848858327055/87.0208096...,219.04756885282941/222.81400066333114/214.0421...,690.0849941195314/692.5944403537776/674.585792...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,2023-12-22,1630.0/1652.0/1622.75/1634.25,10050.0/10318.2998046875/10030.0/10217.150390625,2516.895773491406/2533.8430550362596/2502.9351...,301.96489752724966/306.88177229321946/297.5943...,229.1684551218438/230.3487188419279/226.709566...,2559.60009765625/2580.89990234375/2547.6499023...,644.75/649.4000244140625/635.1500244140625/636.75,1232.971494548331/1243.9091449031953/1229.0439...,716.7999877929688/731.0/712.0/724.7000122070312,...,1401.2339711668026/1436.8278360459776/1393.400...,1660.9194254050005/1663.1884892167195/1644.641...,2559.199951171875/2579.75/2546.800048828125/25...,1002.9500122070312/1009.5499877929688/991.5999...,1574.300048828125/1591.0999755859375/1557.9000...,1534.949951171875/1566.0/1523.0/1562.900024414...,446.4431594702975/449.30117809632634/444.02860...,845.0/857.5499877929688/843.0999755859375/855....,1854.699951171875/1879.6500244140625/1851.0/18...,3424.0/3496.0/3408.60009765625/3477.949951171875
3200,2023-12-26,1640.9000244140625/1669.0/1634.5/1662.25,10270.0/10281.2001953125/10114.7001953125/1027...,2541.4266788005234/2552.7944944020255/2529.360...,304.39849836081004/308.6200469543844/302.56087...,228.18490447743275/231.922418845447/227.250529...,2568.0/2591.949951171875/2562.699951171875/257...,638.8499755859375/641.2999877929688/635.650024...,1236.6008018170903/1242.9147846474198/1232.275...,727.4000244140625/727.5/716.5999755859375/719....,...,1432.274620574288/1436.8279207558985/1412.1521...,1650.7088976124296/1663.2377620371465/1646.072...,2575.60009765625/2591.64990234375/2567.0500488...,994.9000244140625/997.5/989.9000244140625/995....,1562.949951171875/1582.75/1557.0/1570.80004882...,1535.0/1548.0/1523.0/1543.949951171875,449.4489968487372/452.2577511926127/448.118561...,857.5/863.0/849.9500122070312/852.2999877929688,1867.0/1899.0/1857.1500244140625/1886.84997558...,3477.949951171875/3508.35009765625/3477.949951...
3201,2023-12-27,1670.0/1691.800048828125/1660.25/1687.94995117...,10286.0/10305.349609375/10230.0/10288.5,2552.7944007344595/2569.5420501576127/2550.849...,309.51402380742445/310.1596663697173/301.51789...,231.13556193578583/231.97159018423235/228.6766...,2582.0/2599.89990234375/2573.10009765625/2586....,640.75/649.4500122070312/639.0/648.5499877929688,1242.914765688733/1248.2841817521874/1234.2143...,728.0/741.8499755859375/725.1500244140625/740....,...,1434.967487203194/1445.2980870607048/1427.2319...,1658.8477554342537/1683.5109691635766/1655.986...,2586.0/2612.0/2580.89990234375/2608.300048828125,997.9500122070312/1004.9000244140625/992.0/100...,1573.1500244140625/1600.0/1567.300048828125/15...,1544.0/1570.0/1544.0/1567.0999755859375,450.3852670935656/451.863555716411/447.1823084...,858.4500122070312/881.5/855.6500244140625/875....,1894.0/1910.0/1883.1500244140625/1902.34997558...,3510.0/3549.0/3504.14990234375/3544.0
3202,2023-12-28,1688.949951171875/1739.949951171875/1688.40002...,10310.9501953125/10310.9501953125/10187.0/1027...,2579.703650125962/2629.9765450518717/2570.2652...,307.03075985851694/313.38790948752535/305.6897...,231.23392942381133/236.00416511747542/230.2503...,2589.800048828125/2612.0/2586.85009765625/2605...,650.25/653.2999877929688/646.5/651.4000244140625,1247.836709515953/1257.4818013104841/1242.4674...,742.6500244140625/757.9500122070312/739.049987...,...,1440.010282776321/1451.858568886995/1437.90498...,1686.2731985214466/1698.210169182226/1679.0714...,2613.85009765625/2640.0/2606.85009765625/2633....,1008.0/1011.7000122070312/999.0999755859375/10...,1600.0/1618.699951171875/1592.0/1610.550048828125,1568.949951171875/1568.949951171875/1555.0/156...,450.5823856534771/457.97382879033955/449.49830...,882.9000244140625/895.75/874.0/880.7999877929688,1911.0/1926.5/1903.0999755859375/1921.34997558...,3545.0/3559.949951171875/3500.5/3518.050048828125
3203,2023-12-29,1730.0/1758.0/1715.0/1729.4000244140625,10280.4501953125/10396.650390625/10273.0/10302...,2617.611522921542/2657.498936604156/2607.20583...,312.24560649491394/312.24560649491394/306.0870...,233.88953208201474/234.33212911444537/230.8896...,2611.10009765625/2614.0/2579.300048828125/2584...,645.5/649.5999755859375/639.5499877929688/642....,1254.9461608148872/1264.740304927721/1245.4503...,755.0/802.9000244140625/754.0/779.9500122070312,...,1443.2905714281567/1451.0262687914242/1427.231...,1674.1389025534318/1691.7977871899893/1673.152...,2633.800048828125/2667.10009765625/2621.25/266...,1004.0499877929688/1008.5499877929688/993.7000...,1615.0/1618.9000244140625/1587.050048828125/15...,1541.050048828125/1559.449951171875/1540.0/154...,457.3824894142631/461.12747509328545/454.67229...,882.0/887.5/873.2999877929688/880.25,1912.0999755859375/1917.75/1890.050048828125/1...,3531.0/3540.0/3495.0/3526.0

In [18]:
sensex_df.to_csv('Sensex_2011_to_2023.csv')