In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
data=pd.read_csv('/Users/vedantgupta/Documents/summer project/data-analysis-with-technical-indicators-2/Pair Trading final/data/Nifty_50_close.csv')

In [3]:
data

,Date,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BAJAJFINSV.NS,BPCL.NS,...,SBIN.NS,SUNPHARMA.NS,TCS.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
0,2011-01-03,83.153633,134.706543,439.091125,259.076141,251.916626,1036.131714,63.653694,45.593979,60.885281,...,240.419800,222.953842,446.352051,92.316086,245.710632,47.525696,139.034042,172.213837,1034.288086,159.698929
1,2011-01-04,83.358696,137.957016,435.507385,255.619690,248.287949,1003.359985,63.260792,45.380741,60.294853,...,233.050705,224.143417,441.225677,93.640793,243.823334,46.894550,145.471405,170.863922,1036.665527,160.227905
2,2011-01-05,83.576599,146.361649,430.650635,259.612366,241.463486,964.553528,62.998871,45.046360,58.357433,...,229.438522,223.297012,446.698883,92.978455,240.893860,45.966370,142.335739,170.083847,1019.882263,160.558502
3,2011-01-06,82.596054,143.900589,427.349915,256.818451,240.533295,931.816956,62.208553,44.052860,57.084274,...,223.406967,228.764465,451.613007,91.902100,236.800064,46.125011,142.589737,167.194855,961.211853,160.789902
4,2011-01-07,80.506813,136.749664,432.772583,250.171555,235.891541,923.922119,59.580208,43.214451,56.918213,...,221.579605,225.721909,440.416199,89.666672,223.504745,44.636559,138.262314,159.387207,939.246277,157.682205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,2023-12-22,2808.350098,1027.500000,5536.405762,3341.300049,1088.300049,6372.100098,7295.299805,1672.050049,446.649994,...,626.248047,1236.600830,3778.896729,985.917603,724.700012,133.550003,1275.150024,3627.350098,9969.000000,461.665405
3200,2023-12-26,2865.449951,1028.750000,5628.072754,3383.350098,1094.250000,6464.549805,7162.299805,1645.300049,451.600006,...,627.526550,1240.428955,3750.782227,1000.366699,719.549988,135.199997,1282.000000,3656.699951,10018.650391,469.099579
3201,2023-12-27,2843.350098,1024.400024,5682.324219,3404.449951,1106.349976,6709.649902,7232.799805,1669.449951,454.700012,...,637.853394,1245.350830,3766.247559,1019.632263,740.900024,137.199997,1280.150024,3689.250000,10436.099609,469.947784
3202,2023-12-28,2809.899902,1016.950012,5755.308105,3397.250000,1107.849976,6703.299805,7258.649902,1681.199951,465.799988,...,640.656433,1254.995972,3755.080811,1033.783447,753.900024,138.149994,1285.949951,3715.100098,10426.299805,468.450958
3203,2023-12-29,2848.949951,1024.349976,5698.958984,3402.399902,1102.300049,6797.250000,7327.750000,1685.800049,450.649994,...,631.460632,1252.311157,3748.657715,1079.265991,779.950012,139.600006,1272.650024,3675.449951,10503.049805,470.296997

In [4]:
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)
weekly_data = data.resample('W').first()

weekly_data.reset_index(inplace=True)

weekly_data

,Date,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BAJAJFINSV.NS,BPCL.NS,...,SBIN.NS,SUNPHARMA.NS,TCS.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
0,2011-01-09,83.153633,134.706543,439.091125,259.076141,251.916626,1036.131714,63.653694,45.593979,60.885281,...,240.419800,222.953842,446.352051,92.316086,245.710632,47.525696,139.034042,172.213837,1034.288086,159.698929
1,2011-01-16,74.924774,130.388138,446.682709,241.339020,231.093201,885.431335,58.148621,42.477810,55.848026,...,216.992065,218.241302,435.887360,86.313469,220.969604,43.924397,135.361099,153.767944,946.568054,153.599243
2,2011-01-23,78.103516,127.323494,440.269867,239.996140,226.377777,890.097961,57.267994,40.074051,54.025948,...,214.359619,212.933975,438.392639,86.851639,221.373337,42.233444,135.116898,159.999146,961.116760,154.310028
3,2011-01-30,81.487343,132.106247,484.641113,236.219772,244.198822,917.431091,57.945408,40.970615,55.465157,...,229.596161,221.787140,466.066864,87.969368,223.147934,43.826523,135.917892,166.711365,967.772949,146.755707
4,2011-02-06,72.316422,130.527466,463.705078,232.303726,228.809158,874.343567,53.059036,39.623344,56.553787,...,225.110825,201.701630,447.663940,82.339333,215.401688,43.181862,127.175156,168.208435,953.557190,145.489288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,2023-12-03,2423.500000,837.700012,5361.962891,3148.350098,1021.150024,5998.149902,7127.549805,1654.400024,405.349609,...,555.140503,1184.597168,3429.220215,925.390076,697.500000,126.849998,1202.400024,3442.399902,8726.500000,396.005463
674,2023-12-10,2531.199951,878.650024,5617.482422,3194.550049,1125.599976,6201.700195,7407.649902,1696.250000,440.680450,...,584.891602,1224.171631,3471.021240,940.087524,705.599976,131.000000,1223.900024,3488.399902,9317.750000,406.582916
675,2023-12-17,2855.800049,1031.900024,5542.350586,3233.000000,1116.500000,6138.399902,7292.750000,1702.800049,444.500000,...,604.119141,1234.363525,3599.932617,943.861206,720.799988,130.050003,1233.300049,3630.500000,9670.900391,419.704926
676,2023-12-24,2980.600098,1094.300049,5493.693848,3332.050049,1111.349976,6465.700195,7587.600098,1724.599976,447.250000,...,637.804260,1245.649170,3813.681641,943.116394,730.799988,136.600006,1291.750000,3619.600098,9970.349609,444.302460
677,2023-12-31,2865.449951,1028.750000,5628.072754,3383.350098,1094.250000,6464.549805,7162.299805,1645.300049,451.600006,...,627.526550,1240.428955,3750.782227,1000.366699,719.549988,135.199997,1282.000000,3656.699951,10018.650391,469.099579

In [6]:
weekly_data.to_csv('/Users/vedantgupta/Documents/summer project/data-analysis-with-technical-indicators-2/Pair Trading final/data/Nifty_50_close_weekly.csv', index=False)